version: '3'
services:
  nginx:
    build: .\nginx\
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - reader
      - writer

  reader:
    build: .\read\
    hostname: reader
    container_name: reader
    depends_on:
      - redis
 
  writer:
    build: .\write\
    hostname: writer
    container_name: writer
    depends_on:
      - redis

    
  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: redis
    expose:
      - "6379"
 